### ISSUE TITLE
better CMake integration

### ISSUE THREAD

**Issue by spirosmaggioros** [CSRT-NTUA/AlgoPlus#13]
Each folder should have a CMakeLists txt and then integrate them to the main CMakeLists.txt in root dir.

**Comment by CharlesGueunet** [comment]
Using cmake libraires so other CMake project can request components seems the way to go.
Having several `CMakeLists.txt` maybe nice, one per independent sub-projects, like the library, the plugins, ...
Inside the library, you may want to have components that can be enabled disabled.

In any case, I would suggest to avoid `GLOB` completely as this is only evaluated at configure time, so any further changes but developers for example would be omitted.

**Comment by spirosmaggioros** [comment]
This is closed as CMake integration is fine for now
