### ISSUE TITLE
Change value type from int64_t to double in graph.h header

### ISSUE THREAD

**Issue by spirosmaggioros** [CSRT-NTUA/AlgoPlus#52]
The graph.h header file has int64_t value types for distances between edges. It need to be changed to double.

**Comment by adheeshsharma19** [comment]
Hi, can I work on this issue ?

**Comment by spirosmaggioros** [comment]
Sure, if you don't know the codestyle we use you can check the README file as well as the other .md files that we have to guide you on how to contribute(the README.md will guide you on any other file you might need). 
I opened this issue for newcomers to contribute. The issue is that the older version of graph.h file had int64_t value for the distance, thus, the user can't have doubles as a distance value. 
We have test cases for each commit you do, so if anything is wrong we can see it from there, you don't need to run all the test cases yourself.
If you need anything else you can reply to this issue.

**Comment by adheeshsharma19** [comment]
Great, thanks for the opportunity. Will go through the mentioned files and try completing it.

**Comment by spirosmaggioros** [comment]
Issue is still open due to inactivity of participants

**Comment by adheeshsharma19** [comment]
PR raised - https://github.com/CSRT-NTUA/AlgoPlus/pull/53

**Comment by spirosmaggioros** [comment]
This is closed as of commit 7285cbc.
