### ISSUE TITLE
Visualization generator missing from tree.h header

### ISSUE THREAD

**Issue by spirosmaggioros** [CSRT-NTUA/AlgoPlus#60]
the simple tree(tree.h header) was lately added and lacks a visualization generator function. 
You can take the other tree headers as reference to create the generator function(to generate the string) and then to add a simple visualize() function in the class to perform the visualization using the returning string. The graphviz visualization function is ready at vizualization folder, you only need to implement the string generator.

**Comment by aveldan** [comment]
I just reviewed the tree_visualization.h wouldn't the visualization gen for tree.h be also same as that of bst? I just made the tree.h one I can put in a pull request if you don't have it already.

**Comment by spirosmaggioros** [comment]
Yes @aveldan, i mention it on my comment. It's nothing different, of course i can do it myself but i want contributors to do it just to get on groove with the repo and contribute more in the future.

**Comment by spirosmaggioros** [comment]
@aveldan Do you have anything ready for this? I'm asking because you commented on this issue.

**Comment by spirosmaggioros** [comment]
This is closed as of @aveldan 's #74
