### ISSUE TITLE
Red Black tree class

### ISSUE THREAD

**Issue by aveldan** [CSRT-NTUA/AlgoPlus#69]
We do not have red black tree structure as of yet. It is a self balancing binary search tree data structure.

### Concept
[WiKi](https://en.wikipedia.org/wiki/Red%E2%80%93black_tree)

### Thing to impliment
- [X] Structure of the class (including methods like search, remove and traversal)
- [X] Iterator class
- [X] Visualize
- [X] Tests
- [X] Examples

**Comment by spirosmaggioros** [comment]
I did not say we have. I said that i've implemented one for my personal files. But it is not good enough to be in there. The check boxes works for me, looking forward to your PR!

**Comment by spirosmaggioros** [comment]
This is closed. All boxes are checked.
