### ISSUE TITLE
Implement new algorithms 

### ISSUE THREAD

**Issue by spirosmaggioros** [CSRT-NTUA/AlgoPlus#9]
Algorithms folder looks empty. There are plenty of algorithms to add and we are happy to see new contributors do that! 
You can also add test cases and comments for the algorithms.

**Comment by arthiondaena** [comment]
can i implement graph algorithms like FloydWarshall, BellmanFord, etc..

**Comment by spirosmaggioros** [comment]
Sure you can, you can either implement it inside the graph.h or in the algorithms folder, that depends on the implementation you have. Thanks for your interest :)

**Comment by arthiondaena** [comment]
Yeah sure, I will implement them when I have time.

**Comment by spirosmaggioros** [comment]
@dhruvabhat24 I believe all the following algorithms do exist inside algorithms folder
